## Routes
---
# Api
/:                                         { controller: default, action: info }

/scenarios +POST:                          { controller: scenario, action: add }
/scenarios/* +GET:                         { controller: scenario, action: get, id: $2 }

/processes +GET:                           { controller: process, action: list }
/processes +POST:                          { controller: process, action: start }
/processes/* +DELETE:                      { controller: process, action: delete, id: $2 }
/processes/* +GET:                         { controller: process, action: get, id: $2 }
/processes/*/invoke +POST:                 { controller: process, action: invoke, id: $2 }

/processes/*/response +POST:               { controller: process, action: handle-response, id: $2 }
/responses +POST:                          { controller: process, action: handle-response }

/identities +POST:                         { controller: identity, action: put }
/identities/* +GET:                        { controller: identity, action: get, id: $2 }
/identities/* +DELETE:                     { controller: identity, action: delete, id: $2 }
