db:
  default:
    client: !env MONGO_DB mongodb://mongo:27017
    database: !env DB_NAME lto_workflow

services:
  event_chain: null

lto:
  account:
    address: 3N2EVaqEToodweg371JNvGTMHxiS6Gsm9AH
    sign:
      secretkey: wJ4WH8dD88fSkNdFQRjaAhjFUZzZhV5yiDLDwNUnp6bYwRXrvWV8MJhQ9HL9uqMDG1n7XpTGZx7PafqaayQV8Rp
      publickey: FkU1XyfrCftc4pQKXCrrDyRLSnifX1SMvmx1CYiiyB3Y
    encrypt:
      secretkey: BnjFJJarge15FiqcxrB7Mzt68nseBXXR4LQ54qFBsWHG
      publickey: BVv1ZuE3gKFa6krwWJQwEmrLYUESuUabNCXgYTmCoBt6
  network: T