locale: en_US
debug: false
digest: required
noauth: false
http_request_log: false

triggers: []
hooks: []

db:
  default:
    client: !env MONGO_DB mongodb://localhost:27017
    database: lto_workflow

event_chain: null
