locale: en_US
debug: false
digest: required
noauth: false
allow_full_reset: !env ALLOW_FULL_RESET

triggers: []
hooks: []

db:
  default:
    client: !env MONGO_DB mongodb://localhost:27017
    database: lto_workflow

event_chain: null
